name: Flutter Build Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.29.3"
  GRADLE_VERSION: "8.0"
  JAVA_VERSION: "17"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Reorganize project structure
        run: |
          # Déplace le dossier android à la racine
          mv src/lib/android .
          # Vérifie la nouvelle structure
          echo "=== Nouvelle Structure ==="
          ls -R
          [ -f "android/app/build.gradle" ] || exit 1
          [ -f "android/gradle/wrapper/gradle-wrapper.properties" ] || exit 1

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Install dependencies
        run: |
          flutter pub get
          flutter pub upgrade

      - name: Build APK
        run: |
          flutter clean
          flutter build apk --release --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
