name: Flutter Build Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.29.3"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: 'src'

      - name: Verify project structure
        run: |
          echo "=== Project Contents ==="
          ls -R src/
          echo "=== Main Dart File ==="
          find src -name lib/main.dart || echo "Main.dart not found!"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Validate Flutter project
        working-directory: ./src
        run: |
          flutter doctor -v
          if [ ! -f "lib/main.dart" ]; then
            echo "::error::Main Dart file not found at lib/main.dart"
            exit 1
          fi
          echo "Project validated successfully"

      - name: Install dependencies
        working-directory: ./src
        run: |
          flutter pub get
          flutter pub upgrade
          flutter pub outdated

      - name: Build APK
        working-directory: ./src
        run: |
          flutter clean
          flutter build apk --release --verbose
          ls -la build/app/outputs/flutter-apk/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: src/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
