name: Build Flutter APK

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  FLUTTER_CHANNEL: stable
  FLUTTER_VERSION: "3.29.3"  # Version compatible avec shared_preferences 2.3.2+

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20  # Augmentation du timeout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Pour avoir tout l'historique git

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true  # Activation du cache pour les builds plus rapides
          cache-key: flutter-${{ env.FLUTTER_VERSION }}-${{ env.FLUTTER_CHANNEL }}

      - name: Verify Flutter installation
        run: flutter doctor -v

      - name: Install dependencies
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
        timeout-minutes: 5

      - name: Build APK
        run: |
          flutter clean
          flutter build apk --release --no-sound-null-safety --verbose
        timeout-minutes: 10

      - name: Verify APK
        run: |
          APK_PATH="build/app/outputs/flutter-apk/app-release.apk"
          if [ ! -f "$APK_PATH" ]; then
            echo "::error::APK not found at $APK_PATH"
            exit 1
          fi
          echo "APK generated successfully at $APK_PATH"
          ls -lah build/app/outputs/flutter-apk/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7  # Garde l'APK pendant 7 jours
          if-no-files-found: error
