name: Flutter Build Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.29.3"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Recreate Android project
        run: |
          # Sauvegarde des fichiers existants
          mkdir -p backup
          cp -r lib pubspec.yaml backup/
          
          # Recréation propre du projet
          flutter create --platforms android --project-name caldec .
          
          # Restauration du code
          rm -rf lib
          mv backup/lib .
          mv backup/pubspec.yaml .
          rm -rf backup

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Install dependencies
        run: |
          flutter pub get
          flutter pub upgrade

      - name: Build APK
        run: |
          flutter clean
          flutter build apk --release --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
