name: Flutter Build & Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.29.3"

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: 'src'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Verify Environment
        working-directory: ./src
        run: flutter doctor -v

      - name: Resolve Dependencies
        working-directory: ./src
        run: |
          flutter pub get
          flutter pub upgrade
          flutter pub outdated

      - name: Run Build Runner
        working-directory: ./src
        run: flutter pub run build_runner build --delete-conflicting-outputs
        continue-on-error: true

      - name: Build APK
        working-directory: ./src
        run: |
          flutter clean
          flutter build apk --release --verbose
          ls -la build/app/outputs/flutter-apk/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: dreamflow-apk
          path: src/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
