name: Build Flutter APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FLUTTER_CHANNEL: stable
      PROJECT_NAME: caldec

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        channel: ${{ env.FLUTTER_CHANNEL }}

    - name: Cache Flutter Pub dependencies
      uses: actions/cache@v3
      with:
        path: ~/.pub-cache
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pub-

    - name: Get Flutter dependencies
      run: flutter pub get

    - name: Cache Flutter build artifacts
      uses: actions/cache@v3
      with:
        path: |
          build
          .dart_tool
          .flutter-plugins
          .flutter-plugins-dependencies
          .packages
        key: ${{ runner.os }}-build-${{ hashFiles('**/*.dart', '**/*.yaml') }}
        restore-keys: |
          ${{ runner.os }}-build-

    - name: Analyze code (optional but recommended)
      run: flutter analyze

    - name: Run tests (if any)
      run: flutter test || echo "No tests or some tests failed but continue"

    - name: Build APK (release)
      run: flutter build apk --release --no-shrink

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${PROJECT_NAME}-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
