name: Flutter Build Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.29.3"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Recreate Android project
        run: |
          # Sauvegarde des fichiers essentiels
          mkdir _backup
          cp -r lib pubspec.yaml _backup/
          
          # Suppression du dossier android existant
          rm -rf android
          
          # Recréation du projet
          flutter create --platforms android --project-name caldec .
          
          # Restauration des fichiers
          rm -rf lib
          mv _backup/lib .
          mv _backup/pubspec.yaml .
          rm -rf _backup
          
          # Vérification de la structure
          if [ ! -f "android/app/build.gradle" ]; then
            echo "::error::Android project not properly generated"
            exit 1
          fi

      - name: Install dependencies
        run: |
          flutter pub get
          flutter pub upgrade

      - name: Build APK
        run: |
          flutter clean
          flutter build apk --release --verbose
          ls -la build/app/outputs/flutter-apk/

      - name: Verify APK
        run: |
          if [ ! -f "build/app/outputs/flutter-apk/app-release.apk" ]; then
            echo "::error::APK not generated"
            exit 1
          fi
          echo "APK generated successfully"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
