name: Build Flutter APK

on:
  push:
    branches:
      - main  # Exécute le workflow sur chaque push sur la branche 'main'
  pull_request:
    branches:
      - main  # Exécute le workflow sur chaque PR vers 'main'

jobs:
  build_apk:
    runs-on: ubuntu-latest  # Runner Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x.x'  # Compatible avec toutes les versions 3
          channel: stable

      - name: Get Flutter packages
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: caldec-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
