name: Build Flutter APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Permet de déclencher manuellement

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FLUTTER_CHANNEL: stable
      PROJECT_NAME: caldec

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Display Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Cache Pub packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Analyze Dart code (optionnel)
        run: flutter analyze || true

      - name: Run tests (optionnel)
        run: flutter test || echo "No tests found or some failed"

      - name: Build APK
        run: flutter build apk --release --no-shrink

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ env.PROJECT_NAME }}-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          
